# Use the official OpenJDK image as the base image
FROM openjdk:11

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/DevOps_Project-1.0.jar app.jar

# Specify the command to run the Spring Boot application
CMD ["java", "-jar", "app.jar"]